-- CreateTable
CREATE TABLE "paddles" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "brand" TEXT NOT NULL,
    "priceCents" INTEGER NOT NULL,
    "weightOz" REAL,
    "gripCircumference" REAL,
    "coreMaterial" TEXT,
    "faceMaterial" TEXT,
    "shape" TEXT,
    "balancePointMm" INTEGER,
    "powerRating" INTEGER,
    "controlRating" INTEGER,
    "spinRating" INTEGER,
    "sweetSpotSize" TEXT,
    "swingWeight" INTEGER,
    "twistWeight" INTEGER,
    "handleLengthIn" REAL,
    "usapaApproved" BOOLEAN NOT NULL DEFAULT true,
    "imageUrl" TEXT,
    "affiliateUrls" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
