import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const paddles = [
  {
    name: 'Selkirk Vanguard Power Air Invikta',
    brand: 'Selkirk',
    priceCents: 17995,
    weightOz: 8.0,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'elongated',
    balancePointMm: 260,
    powerRating: 9,
    controlRating: 7,
    spinRating: 8,
    sweetSpotSize: 'large',
    swingWeight: 115,
    twistWeight: 6.8,
    handleLengthIn: 5.5,
    usapaApproved: true,
    imageUrl: '/images/paddles/selkirk-vanguard-invikta.jpg',
  },
  {
    name: 'JOOLA Ben Johns Hyperion CFS 16',
    brand: 'JOOLA',
    priceCents: 24995,
    weightOz: 8.3,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 255,
    powerRating: 8,
    controlRating: 9,
    spinRating: 9,
    sweetSpotSize: 'large',
    swingWeight: 118,
    twistWeight: 7.2,
    handleLengthIn: 5.5,
    usapaApproved: true,
    imageUrl: '/images/paddles/joola-hyperion-cfs.jpg',
  },
  {
    name: 'Engage Pursuit Pro MX 6.0',
    brand: 'Engage',
    priceCents: 18995,
    weightOz: 7.9,
    gripCircumference: 4.125,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 252,
    powerRating: 7,
    controlRating: 9,
    spinRating: 8,
    sweetSpotSize: 'medium',
    swingWeight: 112,
    twistWeight: 6.5,
    handleLengthIn: 5.25,
    usapaApproved: true,
    imageUrl: '/images/paddles/engage-pursuit-mx.jpg',
  },
  {
    name: 'Paddletek Tempest Wave Pro',
    brand: 'Paddletek',
    priceCents: 13995,
    weightOz: 7.8,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'graphite',
    shape: 'wide-body',
    balancePointMm: 248,
    powerRating: 7,
    controlRating: 8,
    spinRating: 7,
    sweetSpotSize: 'large',
    swingWeight: 108,
    twistWeight: 6.2,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/paddletek-tempest-wave.jpg',
  },
  {
    name: 'ProKennex Ovation Speed',
    brand: 'ProKennex',
    priceCents: 16995,
    weightOz: 7.5,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'elongated',
    balancePointMm: 265,
    powerRating: 9,
    controlRating: 6,
    spinRating: 7,
    sweetSpotSize: 'medium',
    swingWeight: 120,
    twistWeight: 6.9,
    handleLengthIn: 5.75,
    usapaApproved: true,
    imageUrl: '/images/paddles/prokennex-ovation.jpg',
  },
  {
    name: 'Gamma NeuCore Compass',
    brand: 'Gamma',
    priceCents: 9995,
    weightOz: 7.7,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'fiberglass',
    shape: 'standard',
    balancePointMm: 250,
    powerRating: 6,
    controlRating: 7,
    spinRating: 6,
    sweetSpotSize: 'medium',
    swingWeight: 105,
    twistWeight: 6.0,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/gamma-neucore.jpg',
  },
  {
    name: 'Diadem Warrior Edge 18K',
    brand: 'Diadem',
    priceCents: 21995,
    weightOz: 8.2,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 257,
    powerRating: 8,
    controlRating: 8,
    spinRating: 9,
    sweetSpotSize: 'large',
    swingWeight: 116,
    twistWeight: 7.0,
    handleLengthIn: 5.5,
    usapaApproved: true,
    imageUrl: '/images/paddles/diadem-warrior.jpg',
  },
  {
    name: 'Onix Z5 Graphite',
    brand: 'Onix',
    priceCents: 7995,
    weightOz: 7.5,
    gripCircumference: 4.25,
    coreMaterial: 'nomex',
    faceMaterial: 'graphite',
    shape: 'wide-body',
    balancePointMm: 245,
    powerRating: 7,
    controlRating: 6,
    spinRating: 5,
    sweetSpotSize: 'large',
    swingWeight: 102,
    twistWeight: 5.8,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/onix-z5.jpg',
  },
  {
    name: 'HEAD Radical Elite',
    brand: 'HEAD',
    priceCents: 15995,
    weightOz: 8.1,
    gripCircumference: 4.125,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'elongated',
    balancePointMm: 262,
    powerRating: 8,
    controlRating: 7,
    spinRating: 8,
    sweetSpotSize: 'medium',
    swingWeight: 117,
    twistWeight: 6.7,
    handleLengthIn: 5.5,
    usapaApproved: true,
    imageUrl: '/images/paddles/head-radical.jpg',
  },
  {
    name: 'Franklin Ben Johns Signature',
    brand: 'Franklin',
    priceCents: 19995,
    weightOz: 8.0,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 254,
    powerRating: 7,
    controlRating: 9,
    spinRating: 8,
    sweetSpotSize: 'large',
    swingWeight: 113,
    twistWeight: 6.6,
    handleLengthIn: 5.25,
    usapaApproved: true,
    imageUrl: '/images/paddles/franklin-ben-johns.jpg',
  },
  {
    name: 'Wilson Energy Pro',
    brand: 'Wilson',
    priceCents: 8995,
    weightOz: 7.6,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'fiberglass',
    shape: 'standard',
    balancePointMm: 248,
    powerRating: 6,
    controlRating: 6,
    spinRating: 5,
    sweetSpotSize: 'medium',
    swingWeight: 100,
    twistWeight: 5.5,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/wilson-energy.jpg',
  },
  {
    name: 'Electrum Pro II',
    brand: 'Electrum',
    priceCents: 20995,
    weightOz: 8.3,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'elongated',
    balancePointMm: 268,
    powerRating: 9,
    controlRating: 7,
    spinRating: 8,
    sweetSpotSize: 'medium',
    swingWeight: 122,
    twistWeight: 7.1,
    handleLengthIn: 5.75,
    usapaApproved: true,
    imageUrl: '/images/paddles/electrum-pro.jpg',
  },
  {
    name: 'Vulcan V730 Pro',
    brand: 'Vulcan',
    priceCents: 12995,
    weightOz: 7.9,
    gripCircumference: 4.125,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 251,
    powerRating: 7,
    controlRating: 8,
    spinRating: 7,
    sweetSpotSize: 'large',
    swingWeight: 110,
    twistWeight: 6.4,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/vulcan-v730.jpg',
  },
  {
    name: 'Six Zero Double Black Diamond',
    brand: 'Six Zero',
    priceCents: 22995,
    weightOz: 8.4,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'elongated',
    balancePointMm: 270,
    powerRating: 10,
    controlRating: 6,
    spinRating: 7,
    sweetSpotSize: 'small',
    swingWeight: 125,
    twistWeight: 7.3,
    handleLengthIn: 5.75,
    usapaApproved: true,
    imageUrl: '/images/paddles/six-zero-dbd.jpg',
  },
  {
    name: 'Crbn 1X Power Series',
    brand: 'CRBN',
    priceCents: 23995,
    weightOz: 8.1,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 256,
    powerRating: 8,
    controlRating: 8,
    spinRating: 9,
    sweetSpotSize: 'large',
    swingWeight: 114,
    twistWeight: 6.8,
    handleLengthIn: 5.25,
    usapaApproved: true,
    imageUrl: '/images/paddles/crbn-1x.jpg',
  },
  {
    name: 'Bread & Butter Filth',
    brand: 'Bread & Butter',
    priceCents: 17995,
    weightOz: 8.0,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 253,
    powerRating: 7,
    controlRating: 8,
    spinRating: 8,
    sweetSpotSize: 'medium',
    swingWeight: 111,
    twistWeight: 6.5,
    handleLengthIn: 5.25,
    usapaApproved: true,
    imageUrl: '/images/paddles/bb-filth.jpg',
  },
  {
    name: 'ProLite Titan Pro',
    brand: 'ProLite',
    priceCents: 11995,
    weightOz: 7.8,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'graphite',
    shape: 'wide-body',
    balancePointMm: 247,
    powerRating: 6,
    controlRating: 8,
    spinRating: 6,
    sweetSpotSize: 'large',
    swingWeight: 106,
    twistWeight: 6.1,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/prolite-titan.jpg',
  },
  {
    name: 'Niupipo Explorer Pro',
    brand: 'Niupipo',
    priceCents: 6995,
    weightOz: 7.6,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'fiberglass',
    shape: 'standard',
    balancePointMm: 249,
    powerRating: 6,
    controlRating: 6,
    spinRating: 5,
    sweetSpotSize: 'medium',
    swingWeight: 98,
    twistWeight: 5.4,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/niupipo-explorer.jpg',
  },
  {
    name: 'Vatic Pro Flash',
    brand: 'Vatic',
    priceCents: 8995,
    weightOz: 7.7,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'standard',
    balancePointMm: 250,
    powerRating: 7,
    controlRating: 7,
    spinRating: 7,
    sweetSpotSize: 'medium',
    swingWeight: 107,
    twistWeight: 6.3,
    handleLengthIn: 5.0,
    usapaApproved: true,
    imageUrl: '/images/paddles/vatic-flash.jpg',
  },
  {
    name: 'Gearbox CX14E Ultimate Power',
    brand: 'Gearbox',
    priceCents: 19995,
    weightOz: 8.5,
    gripCircumference: 4.25,
    coreMaterial: 'polymer',
    faceMaterial: 'carbon fiber',
    shape: 'elongated',
    balancePointMm: 272,
    powerRating: 10,
    controlRating: 6,
    spinRating: 7,
    sweetSpotSize: 'small',
    swingWeight: 127,
    twistWeight: 7.5,
    handleLengthIn: 5.75,
    usapaApproved: true,
    imageUrl: '/images/paddles/gearbox-cx14e.jpg',
  },
];

async function main() {
  console.log('Starting seed...');

  // Clear existing paddles
  await prisma.paddle.deleteMany({});
  console.log('Cleared existing paddles');

  // Create paddles
  for (const paddle of paddles) {
    await prisma.paddle.create({
      data: paddle,
    });
    console.log(`Created paddle: ${paddle.name}`);
  }

  console.log(`Seed completed! Created ${paddles.length} paddles.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
